name: Weather - Profile README
author: bumb7ebee
description: Update your README.md file with the weather of a city

branding:
  color: yellow
  icon: cloud-rain

inputs:
  weather-api-key:
    description: "OpenWeather API key"
    required: true
  city-id:
    description: "Numerical ID of the city"
    required: true
  metric:
    description: "Centigrade (c) or Fahrenheit (f)"
    required: false
    default: 'c'
  readme-path:
    description: "README.md file path"
    required: false
    default: 'README.md'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ github.action_path }}/requirements.txt
    - name: Pass inputs to shell
      shell: bash
      run: |
        echo "INPUT_WEATHER_API_KEY=${{ inputs.weather-api-key }}" >> $GITHUB_ENV
        echo "INPUT_CITY_ID=${{ inputs.city-id }}" >> $GITHUB_ENV
        echo "INPUT_METRIC=${{ inputs.metric }}" >> $GITHUB_ENV
        printf "PATH_README=%s/%s\n" $GITHUB_WORKSPACE ${{ inputs.readme-path }} >> $GITHUB_ENV
    - name: Run script
      shell: bash
      run: |
        python -u ${{ github.action_path }}/src/main.py
